# Generated by Django 6.0.7 on 2026-08-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_messenger',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Аккаунт MAX'),
        ),
    ]
