# Generated by Django 6.0.7 on 2026-07-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0008_dogparent_is_active_dogparent_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogparent',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='dogparent',
            name='owner',
        ),
        migrations.AddField(
            model_name='dog',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
    ]
