# Generated by Django 6.0.7 on 2026-08-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0009_remove_dogparent_is_active_remove_dogparent_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='views',
            field=models.ImageField(default=0, upload_to='', verbose_name='Просмотры'),
        ),
    ]
