# Generated by Django 6.0.7 on 2026-08-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0010_dog_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
