# Generated by Django 6.0.7 on 2026-08-04 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='sing_of_review',
            new_name='sign_of_review',
        ),
    ]
